# Generated by Django 4.0.3 on 2022-04-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
