# Generated by Django 4.0.3 on 2022-04-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promapp', '0002_alter_student_dateemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalemaildata',
            name='date_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
